version: '3.8'

services:

  hugo:
    image: HUGO_IMAGE:${HUGO_VERSION}
    deploy:
      labels:
        - traefik.constraint-label=traefik
        - traefik.docker.network=traefik
        - traefik.enable=true
        - traefik.http.services.hugo.loadbalancer.server.port=80

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        #- traefik.http.middlewares.hugo-auth.basicauth.users=root:${HUGO_HASHED_PASSWORD}

        # Router: HTTP
        - traefik.http.routers.hugo-http.rule=Host(`*HOST*`)
        - traefik.http.routers.hugo-http.entrypoints=http
        - traefik.http.routers.hugo-http.middlewares=https-redirect

        # Router: HTTPS
        - traefik.http.routers.hugo-https.rule=Host(`*HOST*`)
        - traefik.http.routers.hugo-https.entrypoints=https
        - traefik.http.routers.hugo-https.tls=true
        - traefik.http.routers.hugo-https.tls.certresolver=le
        #- traefik.http.routers.hugo-https.middlewares=hugo-auth

    networks:
      - traefik

networks:
  traefik:
    external: true
